[build-system]
requires = [
    "scikit-build-core>=0.5",
    "pybind11",
    "cmake>=3.22",
    "ninja",
    "torch",  # Required so CMake can find Torch during build
    "numpy"
]
build-backend = "scikit_build_core.build"

[project]
name = "polymetis"
version = "0.1.0"
description = "Polymetis Python Wrapper"
readme = "README.md"
requires-python = ">=3.10" # need sufficiently recent version to have grpcio wheels available
dependencies = [
    "numpy",
    "torch",
    "pyyaml",
    "grpcio==1.46.*", # must match conda version
    "protobuf==3.20.*", # must match conda version
    "hydra-core>=1.3.2",
]

[tool.scikit-build]
# Points to the directory containing the root CMakeLists.txt
cmake.source-dir = "polymetis"

build-dir = "build"

# PASSING CONDA ENVIRONMENT TO CMAKE
# We map the $CONDA_PREFIX environment variable to CMAKE_PREFIX_PATH.
# This tells CMake: "Look for libraries here first."
cmake.args = [
    "-DCMAKE_PREFIX_PATH=$CONDA_PREFIX",
    "-DCMAKE_FIND_ROOT_PATH=$CONDA_PREFIX",
    "-DCMAKE_PROGRAM_PATH=$CONDA_PREFIX/bin", 
    "-DCMAKE_LIBRARY_PATH=$CONDA_PREFIX/lib",
    "-DCMAKE_INCLUDE_PATH=$CONDA_PREFIX/include",
    "-DCMAKE_NO_SYSTEM_FROM_IMPORTED=ON"
]

wheel.packages = ["polymetis/python/polymetis", "polymetis/python/hydra_plugins", "polymetis/python/torchcontrol"]

# This ensures the resulting wheel is platform-specific (contains compiled code)
wheel.expand-macos-universal-tags = true

build.verbose = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.black]
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | third_party
)/
'''
